"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _home_page from './home-page.bones.json'

registerBones({
  "home-page": _home_page,
})
